apiVersion: v1
kind: ConfigMap
metadata:
  name: pharma-ui
  namespace: dev
  labels:
    app: pharma-ui
    version: "1.0.0"
data:
  API_BASE_URL: "http://dev.vhbj.site/api"
  AUTH_BASE_URL: "http://dev.vhbj.site/auth"
  ENV: dev
